#This action going to handle the testing and if any failure will send the email.


name: Testing Job
on:
  push:
    branches:
      - "dev"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 14, 16, 18 ]
    name: Node ${{ matrix.node }} sample
    steps:
      - name: Gitclone
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Run the test case    
        run: | 
          npm install
          npm run cover
    


  

